"""empty message

Revision ID: 73f729699b92
Revises: 
Create Date: 2022-05-04 21:23:52.656351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f729699b92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'subject',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('posts', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('replies', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('post', 'replies', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('post', 'replies', 'posts', ['post_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.alter_column('replies', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('posts', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('posts', 'subject',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
