"""empty message

Revision ID: c3352b167507
Revises: 
Create Date: 2022-05-03 23:19:58.048595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3352b167507'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Replies')
    op.drop_table('People')
    op.drop_table('Posts')
    op.alter_column('posts', 'subject',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('posts', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('replies', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('replies', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('post_id', 'replies', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('post_id', 'replies', 'posts', ['post_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.alter_column('replies', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('replies', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('posts', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('posts', 'subject',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_table('Posts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Posts_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Posts_pkey')
    )
    op.create_table('People',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"People_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('catchphrase', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='People_pkey')
    )
    op.create_table('Replies',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Replies_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Replies_pkey')
    )
    # ### end Alembic commands ###
